// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLIa78EbsgPXypBCrlFJXYdKXOVr2kwCw',
    appId: '1:179900082745:web:bc72e7c0f76ff016b0bbe8',
    messagingSenderId: '179900082745',
    projectId: 'onyx-c4702',
    authDomain: 'onyx-c4702.firebaseapp.com',
    storageBucket: 'onyx-c4702.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHHWjChNNFUMfhji1OnbesW0M5HO39YSw',
    appId: '1:179900082745:android:6a265e5fc36c4a3fb0bbe8',
    messagingSenderId: '179900082745',
    projectId: 'onyx-c4702',
    storageBucket: 'onyx-c4702.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs3Tv3CwkbbeheOQHoV21h_MyFAgTjBQk',
    appId: '1:179900082745:ios:89d58230dce269c8b0bbe8',
    messagingSenderId: '179900082745',
    projectId: 'onyx-c4702',
    storageBucket: 'onyx-c4702.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLIa78EbsgPXypBCrlFJXYdKXOVr2kwCw',
    appId: '1:179900082745:web:80d55a54178e72fcb0bbe8',
    messagingSenderId: '179900082745',
    projectId: 'onyx-c4702',
    authDomain: 'onyx-c4702.firebaseapp.com',
    storageBucket: 'onyx-c4702.firebasestorage.app',
  );
}
