name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Manual Flutter Install (Bypass Extraction Freeze)
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Initialize Flutter
        run: flutter precache

      # 1. قفل تحليلات فلاتر عشان السيرفر ميعلقش مستني إجابة (y/n)
      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      

      # 3. إضافة حرف (-v) عشان يطبع كل خطوة بالتفصيل الممل وميعلقش في صمت
      - name: Build release APK
        run: flutter build apk --release -v

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk