name: Build Flutter APK

on:
  push:
    branches: [ main ] # هيشتغل كل ما ترفع كود جديد
  workflow_dispatch: # تقدر تشغله يدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: onyx-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk