name: Onyx Stock Monitor

on:
  schedule:
    - cron: '*/15 * * * *' # التشغيل أوتوماتيك كل 15 دقيقة
  workflow_dispatch: # زرار يدوي عشان تجرب السكريبت في أي وقت

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create Firebase Key File from Secret
        run: |
          echo '${{ secrets.FIREBASE_JSON }}' > firebase-key.json

      - name: Run Monitor Script
        run: python monitor.py